### ISSUE TITLE
Mod is partial working for me...

### ISSUE THREAD

**Issue by MrSlick66** [swolewizard/EpicValheimAdditions#10]
This Mod seem to be partial working for me. I can get the resources to make the new gear but can not actually craft it or even get a unlock when I pick up these items. Not sure what the issue is.... I have went into debug mode and it does not show them to even be craftable. Tried to put down thors forge to see if that was it but nothing seems to work. Also not sure if the Boss alter are spawned in and the npc in the new biome do not drop items not sure if this a different mods issue.

**Comment by swolewizard** [comment]
Not this mods issue

**Comment by MrSlick66** [comment]
Super helpful. Epic Valheim was the issue switched to Journey to Valheim everything works. For anyone who stumbles across this and is looking for a real answer.

**Comment by swolewizard** [comment]
Oh so this mod wasn't the issue all along, it's almost like I said that.

Should've looked for help at epic valheim
