### ISSUE TITLE
Thor's Forge recipes don't show up at all without nocost

### ISSUE THREAD

**Issue by daltonyxdonovan** [swolewizard/EpicValheimAdditions#12]
this very well may not be a bug, but i've tried all i can think of to correct it.

Latest version of the mod, latest valheim version.

I've tried reinstalling it to both the server and the client and the problem still persists. With nocost on, i can SEE the recipes that i have available with my materials (i have all the items for frometal stuff for instance, and should be able to craft it) however, with nocost off no one has any available recipes for the forge. When the forge and inscription table were both placed, both said tier 6 tables were created. Any pointers I could be missing?

**Comment by swolewizard** [comment]
Test if this issue persists with only EVA installed.

**Comment by cetharel** [comment]
Had same issue, buy a thunderstone from the shop and the recipies pops up :)
