### ISSUE TITLE
missing Frometal tools

### ISSUE THREAD

**Issue by ToreiCZ** [swolewizard/EpicValheimAdditions#15]
Hello,

Im trying to unlock Frometal axe and pickaxe, but we have everything needed but its still not showing in Thors Forge.

Isnt it affected by the Mistlands update and not spawning heavy metal content?

Like you forget to change unlock recipe from black metal which is vanilla content for mistlands and its still waiting for heavy metal unlock but its literally not in the game.

Tried to contact you via discord, but im not able to find your so I hope you will read there my message.

**Comment by swolewizard** [comment]
they need the jotunn trophy
