### ISSUE TITLE
Jotunn loses aggro below 20%ish health

### ISSUE THREAD

**Issue by TheRiddler13** [swolewizard/EpicValheimAdditions#16]
After getting Jotunn health to about 15 - 20 % boss had stopped attacking me, (melee fight) and ran partially away and attacked with range attack once and then lost aggro for the rest of the fight and even ended up going unalerted (the boss bar went away when I was right next to the boss) after getting the sneak attack bonus boss would still not aggro after this point and kept running around aimlessly

**Comment by swolewizard** [comment]
This is intended.
