### ISSUE TITLE
Conflict problem with wackysDatabase!？

### ISSUE THREAD

**Issue by Taotaolxt** [swolewizard/EpicValheimAdditions#17]
I changed the name and data of the armour in my original game via the wackysDatabase mod, but the changed item is the armour from EVA, why is this?
The pre-made name of the equipment I modified by the original game is: ArmorPaddedCuirass
But the actual modded gear is EVA's gear with the pre-made name: EVA_BlazingBoots
Are you able to view why this is?

**Comment by swolewizard** [comment]
I don't know how to fix issues or conflicts with other mod authors' mods. You would have to submit this bug on their end and see if it's a bug from their mod first. The only thing I can think of as to why this is the case is that the EVA_Blazing armor was created from the original model of the Padded cuirass armor.
