### ISSUE TITLE
change the language of the items

### ISSUE THREAD

**Issue by SpanisHammer** [swolewizard/EpicValheimAdditions#18]
First of all, thank you for this very useful and fun mod that gives us more hours to play this game. I am Spanish and although my English is acceptable on the server that several of my friends play on, not everyone speaks English. Is there any way to translate the names and descriptions of the items into another language? As for example such as adding a file to the "translations" folder called  "EVA.spanish.json" as in other mods
Thank you

**Comment by swolewizard** [comment]
It is possible, but it would be a huge project to undertake. This would involve going through every item, location, and mob in the mod and changing their name to a specific token. Afterwards, a separate .json file would need to be created for each language, which would reference every token for translation. I would consider undertaking this project if JVL makes the process a lot simpler, but as of now, I am not actively working on this mod. However, I will fix any bugs that are reported.
