### ISSUE TITLE
Custom boss altar

### ISSUE THREAD

**Issue by OvidiuBr** [swolewizard/EpicValheimAdditions#19]
Hello,i'm using Journey to valhala modpack wich have EVA,and after 300+days of gameplay i dont find custom altar boss.I testing in new maps and this custom altar spawn near starting location.(i testing around 10 new maps)
![Boos custom spawn](https://github.com/swolewizard/EpicValheimAdditions/assets/140942391/7746230f-317a-402c-a5fd-4cff0b6c228a)
**I don't want to lose all the progress in the game, and I would like to know if it is possible for this POI to be much further from the starting area ?**

![2](https://github.com/swolewizard/EpicValheimAdditions/assets/140942391/2bb32d69-4f85-42c5-8bd3-5c2950bb4cae)

seed is : QHefHTmGps

**Comment by swolewizard** [comment]
Follow the guide on the EVA mod pages comments, to generate locations on worlds.
