### ISSUE TITLE
SvartalfrQueen Vegvisir dosent function

### ISSUE THREAD

**Issue by Morpheus1101** [swolewizard/EpicValheimAdditions#22]
We started a brand new map a few days ago on a dedicated SMP server and finally found the Vegvisir for the SvartalfrQueen however when clicking on it, no locations show up on the map and no errors appear in console on client or server.

**Comment by swolewizard** [comment]
Tested with only my mod installed.
I've created a new character and a new world with 'Mistlands' and 'Mistlandslocations' toggled to 'true' in the configuration settings to investigate if there might be an issue with the locations not spawning correctly.  After some testing, I can confirm that everything is indeed spawning as expected on my end.

However, I have also identified an issue with the Vegvisir not pinning the boss altars on the map. I plan to fix this problem soon, no need for concern though, as long as the Vegvisir has spawned, the altar would have spawned as well; it might just require a bit more effort to locate.

![working](https://i.imgur.com/vTaMzOn.jpg)
![working](https://i.imgur.com/5etw6W0.png)

**Comment by Morpheus1101** [comment]
How did you come across doing the last picture showd?

**Comment by swolewizard** [comment]
> How did you come across doing the last picture showd?

It's a mod on JVL's Discord server, designed as a tool to assist mod developers in gaining a clearer visual representation of how their mods locations are spawning in the world.

> We started a brand new map a few days ago on a dedicated SMP server and finally found the Vegvisir for the SvartalfrQueen however when clicking on it, no locations show up on the map and no errors appear in console on client or server.

I've just released a fix for the Vegvisirs in mod version 1.9.5.

**Comment by Morpheus1101** [comment]
When clicking the Vegvisir it now registers it and indeed show the brief txt on screen pertaining to the Svartalfar Queen, but no map pin shows up on the map.

Sever console shows, but no map pin location shows: 
09/23/2023 05:25:59: Found location of type SvartalfrQueenAltar_New

**Comment by swolewizard** [comment]
> When clicking the Vegvisir it now registers it and indeed show the brief txt on screen pertaining to the Svartalfar Queen, but no map pin shows up on the map.
> 
> Sever console shows, but no map pin location shows: 09/23/2023 05:25:59: Found location of type SvartalfrQueenAltar_New

The issue appears to be on your end. I've successfully tested the mod on both single-player and a fresh dedicated server, and I can confirm that the location is correctly pinned on the map when I interact with the vegvisir on both.

I can suggest to:
Make sure the server and client both have their EVA & JVL updated.
Create a fresh new single player world and spawn in a vegvisir with 'location vegvisir_svartalfrqueen' and see if it'll correctly pin on singleplayer.

Dedicated server screenshots.
![working](https://i.imgur.com/hQy7G35.jpg)
![working](https://i.imgur.com/vfFrSWj.jpg)
