### ISSUE TITLE
No Crafiting item show

### ISSUE THREAD

**Issue by PKLee01** [swolewizard/EpicValheimAdditions#23]
Hello, I don't know what i am do wrong but i am unable to see all crafting lists in the crafting table (Thor's Forge and Inscription Table).
Please help!

![image](https://github.com/swolewizard/EpicValheimAdditions/assets/146119435/2edda862-2e6a-4435-9808-1c116e3afe21)
![image](https://github.com/swolewizard/EpicValheimAdditions/assets/146119435/5d5730d2-b59c-4a4f-9e34-8a29eae7bb45)

**Comment by swolewizard** [comment]
Make sure you've discovered all the required crafting materials, in order for anything to show up at the crafting bench
