### ISSUE TITLE
Deep Abyss Weapons | Weapons Registering Attacks Against Mobs

### ISSUE THREAD

**Issue by ValhallaCommunity** [swolewizard/EpicValheimAdditions#24]
Hey Huntardy!

Hope all is going well! I run a dedicated server, about 40-50 concurrent players. Been trying the Deep Abyss Weapons, since the 2.0.1, they haven't been hitting creatures but worked on prior version. 

I recorded a video, but it was too big for GH. Happy to share on Disc!

Thanks!

**Comment by swolewizard** [comment]
I tested it just now with only EVA 2.0.1 installed, and all Abyss weapons successfully hit mobs. You can upload your video to YouTube and share the link, but it's likely to be related to a mod conflict issue or a dedicated server type issue.
