### ISSUE TITLE
Enhancement Request: Mod Split Inquiry

### ISSUE THREAD

**Issue by ValhallaCommunity** [swolewizard/EpicValheimAdditions#25]
Hey Huntardy, me again! 

We love your mod! Have you explored splitting EVA into Creatures, Weapons, and Vegetation mods? Looking to optimize space for the multiplayer experience (which Valheim notoriously isn't great at scale). We use the weapons and creatures, but mostly turn vegetation off. Let me know your thoughts! Thank you for considering and hearing me out! Excited for the new update!

**Comment by swolewizard** [comment]
As of now, I don't have any intentions to split my mod into multiple others. You can achieve this effect with the current configuration.
