### ISSUE TITLE
I found a issue on the newest version on the valheim epic additions mod

### ISSUE THREAD

**Issue by kolibo** [swolewizard/EpicValheimAdditions#26]
so in order to make the thors forge i need the flame world tree fragment that can only be chopped down from frometal axe right ? But in order to make a frometal axe the recipe shows up only in the thors forge when i tested it on a diffrent server. In the cold forge only the formetal buckler shows up . Is this an issue with the mod , or i have installed something that intervened with your mod...
Tell me because i have been stuck looking for comment sections , videos for hours and still havent found anyone with the same problem with me...

**Comment by swolewizard** [comment]
you're using a modpack that changes my mod.

**Comment by kolibo** [comment]
![Screenshot_20231029_094449](https://github.com/swolewizard/EpicValheimAdditions/assets/149266012/b8c249e1-3192-45db-8a1d-5ceda94f95b3)

**Comment by kolibo** [comment]
can u tell me which of these ones might cause the problem it would really save me some time from removing them one by one and seeing the diffrence. Just tell me your opinion on the one u are suspecting to be causing the issue.

Thank again for taking the time to awnser my issue :)

**Comment by swolewizard** [comment]
Jtv and Jtv biomes
