### ISSUE TITLE
No trees and shrooms in North biome

### ISSUE THREAD

**Issue by gironnimooe** [swolewizard/EpicValheimAdditions#28]
Playing on dedicated server with several mods, so far no problems. The only one i am forcing is that i dont have any mushrooms or trees in the north biome so far :/

**Comment by swolewizard** [comment]
Ensure that you utilize this mods custom **Upgrade World** commands, to generate all EVA vegetation and determine locations on your server's world. I highly recommend downloading and installing the mod '[Upgrade World](https://www.nexusmods.com/valheim/mods/1485)' on both your client and server. After installation, execute the 'EVA_upgrade' command in the '**F5**' console to initiate the process.

https://github.com/swolewizard/EpicValheimAdditions/blob/8c1af5509fdfcc159133953a459d9c13ea44332f/EpicValheimAdditions.cs#L69
