### ISSUE TITLE
Game breaking Camera bug for Improved Skills Valheim mod

### ISSUE THREAD

**Issue by OzaKahuu** [swolewizard/EpicValheimAdditions#4]
So, I'm having this problem where if i ONLY enable Improved Skills Mod then when i load into the world the The Camera just spins uncontrollably and all my movement inputs are ignored, and my character is sitting down AND Sneaking, so I have no idea of what's causing it

Side Note: My Valheim is on Steam and it's Super Unstable and I have no idea why and it's still unstable After I Reinstall it and Checked file integrity

**Comment by swolewizard** [comment]
This is not an issue caused by my mod
