### ISSUE TITLE
FroMetal textures and particle effects missing

### ISSUE THREAD

**Issue by ghost** [swolewizard/EpicValheimAdditions#5]
All the FroMetal weapons and ingots have broken/missing particle effects. I started a new character on a new world with no mods and went through the version history of EpicValheimAdditions. The last version that shows the textures/particle effects correctly for me was version 1.7.2. As soon as I download a version higher than that I only see a gray untextured model and strange square particles dripping down. No frost effects and no blue glow.

I did this testing with no other mods installed on a new profile of R2Modman, using a new character and a new world. The only mod I had to use was EasySpawner to spawn in the frometal items for testing.

I normally run the game with directx, but I've also tried Vulcan but no help there. Also interesting is the the FlaMetal items all look good still. I only have issues with the FroMetal items on version 1.7.3 and up to current version of the mod.

**Comment by swolewizard** [comment]
Thanks for reporting this issue, seems a valheim update broke the colors I made for frometal weapons/tools, I'll fix it in 1.8.3 within  a couple hours from now.

Edit: Fixed in 1.8.3

**Comment by ghost** [comment]
Thanks! You're awesome!
