### ISSUE TITLE
Other players can't see boss altars

### ISSUE THREAD

**Issue by Lime18** [swolewizard/EpicValheimAdditions#7]
Also they are not saved in the world, after re-entering the world they disappear
![image](https://user-images.githubusercontent.com/29817277/190828083-35e596b3-8ea0-456e-8c50-4f8596a3354b.png)

**Comment by swolewizard** [comment]
Find naturally spawning altars, spawning in altars with commands don't save in the world

**Comment by Lime18** [comment]
Thanks for the quick response.
Hoped I could add custom spawns

**Comment by swolewizard** [comment]
I think there's a way, but you'd have to ask others. I've forgotten how I did it once before.
