### ISSUE TITLE
Ancient Root Not Generating

### ISSUE THREAD

**Issue by Morpheus1101** [swolewizard/EpicValheimAdditions#9]
We've been through a few Mistlands Biomes and while we're using the Biome Flora Mod from Horem that adds in vegetation to that area, we've not come across any Ancient Roots in which to harvest, is there another or better biome generation mod we need to be running in order to get this so we can get the Crafting table to make better weapons//tools?

**Comment by swolewizard** [comment]
Use JTV Biomes
